name = "ConvolutionInterpolations"
uuid = "75b5ba44-29d7-490a-960d-52c835d47405"
version = "0.5.1"
authors = ["Nikolaj Maack Bielefeld"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
LinearAlgebra = "1.0.0 - 1.12.0"
Scratch = "1.0.0 - 1.3.0"
Serialization = "1.0.0 - 1.11.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
